### PR TITLE
structs/MultiMatch: Add endTime

### PR DESCRIPTION
**Pull request by ThePooN**
**This PR is based on PR #21 (as it includes updates to the typings in that PR). Please merge #21 first.**

### CODE REVIEW

**Comment by nicholastay** [comment]
Again, thanks so much for these PRs. I've finally got around to merging them and I'll be publishing them soon enough. I really haven't had that much time to keep up to date with osu! API changes lately as well as the fact that I don't really play the game too much anymore. Perhaps I should add you as a contributor? Anyway thanks again!

**Comment by ThePooN** [comment]
I think you mean contributor in the sense of maintainer (with rights to push to GitHub/npm)? Because as it stands, I'm already a contributor by getting PRs merged. :stuck_out_tongue:

**Comment by nicholastay** [comment]
Yeah, that's what I meant haha

**Comment by ThePooN** [comment]
I dunno really, I guess that's up to you whether you still want to review my updates or let me directly just push them.

**Pull request merged**
